// Helper to create slugs from developer names
export function createDeveloperSlug(developerName: string): string {
  return developerName
    .toLowerCase()
    .replace(/\s+properties$/i, '')
    .replace(/\s+realty$/i, '')
    .replace(/\s+/g, '-')
    .replace(/[^a-z0-9-]/g, '');
}

// Generate project URL in format: /projects/{developer-slug}/{project-id}
export function getProjectUrl(projectId: string | number, developer: string): string {
  const developerSlug = createDeveloperSlug(developer);
  return `/projects/${developerSlug}/${projectId}`;
}

// Map of known projects to their developers for routing
export const projectDeveloperMap: Record<string, string> = {
  'breez': 'danube',
  'timez': 'danube',
  'sparklz': 'danube',
  'shahrukhz': 'danube',
  'aspirz': 'danube',
  'bayz102': 'danube',
  'oasiz': 'danube',
  'oasiz2': 'danube',
  'damac-islands-2': 'damac',
  'damac-district': 'damac',
  'chelsea-residences': 'damac',
  'safa-gate': 'damac',
  'riverside-views': 'damac',
  'violet-4': 'damac',
  'sun-city': 'damac',
  'damac-islands': 'damac',
  'shoreline': 'damac',
  'elo-3': 'damac',
  'burj-azizi': 'azizi',
  'aliyah': 'azizi',
  'creek-views': 'azizi',
  'aura': 'azizi',
  'azizi-david': 'azizi',
  'prestige-one-residences': 'prestige-one',
  'sunvale': 'prysm',
  'binghatti-luxuria': 'binghatti',
  'binghatti-cullinan': 'binghatti',
  'binghatti-hillcrest': 'binghatti',
  'binghatti-titania': 'binghatti',
  'binghatti-vintage': 'binghatti',
  'samana-boulevard': 'samana',
  'samana-hills-south-3': 'samana',
  'samana-hills-south-2': 'samana',
  'samana-imperial': 'samana',
  'samana-sky-views': 'samana',
  'rukan-tower': 'reportage',
  'perla-prime': 'reportage',
  'r-hills': 'reportage',
  'via': 'reportage',
  'the-grove': 'sobha',
  'the-greens': 'sobha',
  'the-brooks': 'sobha',
  'the-pinnacle': 'sobha',
  'skyvue-altier': 'sobha',
  'city-walk-crestlane': 'meraas',
  'city-walk-crestlane-4': 'meraas',
  'city-walk-crestlane-5': 'meraas',
  'the-edit-d3': 'meraas',
  'nad-al-sheba-gardens-phase-11': 'meraas',
  'nad-al-sheba-gardens': 'meraas',
  'mjl-nourelle': 'meraas',
  'jumeirah-emirates-tower': 'meraas',
  'meriden-beach': 'green-horizon',
  'damac-casa': 'damac',
  'volta': 'damac',
  'coral-reef': 'damac',
  'elegance-tower': 'damac',
  'canal-heights': 'damac',
  'la-tilia': 'dubai-properties',
  'mudon-al-ranim-7': 'dubai-properties',
  'mudon-al-ranim-5': 'dubai-properties',
  'eltiera-views': 'ellington',
  'meriva-collection': 'ellington',
  'windsor-house-ii': 'ellington',
  'sea-cliff-by-imtiaz': 'imtiaz',
  'salva': 'emaar',
  'grove-ridge': 'emaar',
  'vista-ridge': 'emaar',
  'albero-at-dubai-creek-harbour': 'emaar',
  'golf-meadow-at-emaar-south': 'emaar',
  'golf-verge-at-emaar-south': 'emaar',
  'golf-dale-at-emaar-south': 'emaar',
  'parkwood-at-dubai-hills-estate': 'emaar',
  'sera-1': 'emaar',
  'sera-2': 'emaar',
  'grand-polo-chevalia-estate-2': 'emaar',
  'grand-polo-equiterra-2': 'emaar',
  'ovelle-at-the-valley': 'emaar',
  'symphony-by-chaimaa': 'chaimaa',
  'blossom-40': 'tranquil',
  'art-house-hills': 'adaan',
  'palm-central-private-residences': 'nakheel',
  'zyra-hills': 'laraix',
  'murooj-al-furjan': 'nakheel',
  'tilal-al-furjan': 'nakheel',
  'canal-front-residences': 'nakheel',
  'alba-residences': 'omniyat',
  'orla-dorchester-collection': 'omniyat',
  'vela-viento-dorchester-collection': 'omniyat',
  'peninsula-four-the-plaza': 'select-group',
  'artistry-one-residences': 'select-group',
  'artistry-two-residences': 'select-group',
  'jumeirah-living-business-bay': 'select-group',
  'six-senses-residences-dubai-marina': 'select-group',
  'derby-heights': 'amis',
  'art-house-private-residences': 'viva',
  'palace-residences-hillside-b': 'emaar',
  'linea-by-holm': 'holm',
};
